export enum UserErrors {
  USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  NO_USER_FOUND = "NO_USER_FOUND",
  WRONG_CREDENTIALS = "WRONG_CREDENTIALS",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  REGISTRATION_ERROR = "REGISTRATION_ERROR",
  LOGIN_ERROR = "LOGIN_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
  SERVER_ERROR = "SERVER_ERROR"
}
